import React from 'react';
import SvgIcon from '../components/SvgIcon';

export const icons = {
  myeduquiz: (props) => <SvgIcon name="myeduquiz" {...props} />,
  wifi: (props) => <SvgIcon name="wifi" {...props} />,
  tabHome: (props) => <SvgIcon name="tabHome" {...props} />,
  tabAssignment: (props) => <SvgIcon name="tabAssignment" {...props} />,
  tabNotification: (props) => <SvgIcon name="tabNotification" {...props} />,
  tabProfile: (props) => <SvgIcon name="tabProfile" {...props} />,
  tabCompleted: (props) => <SvgIcon name="tabCompleted" {...props} />,
  user: (props) => <SvgIcon name="user" {...props} />,
  password: (props) => <SvgIcon name="password" {...props} />,
  faceId: (props) => <SvgIcon name="faceId" {...props} />,
  touchId: (props) => <SvgIcon name="touchId" {...props} />,
  noti: (props) => <SvgIcon name="noti" {...props} />,
  notiFill: (props) => <SvgIcon name="noti.fill" {...props} />,
  avatar: (props) => <SvgIcon name="avatar" {...props} />,
  back: (props) => <SvgIcon name="back" {...props} />,
  info: (props) => <SvgIcon name="info" {...props} />,
  goalGreen: (props) => <SvgIcon name="goalGreen" {...props} />,
  goalOrange: (props) => <SvgIcon name="goalOrange" {...props} />,
  goalRed: (props) => <SvgIcon name="goalRed" {...props} />,
  readAloud: (props) => <SvgIcon name="readAloud" {...props} />,
  speechOnTopic: (props) => <SvgIcon name="speechOnTopic" {...props} />,
  sentences: (props) => <SvgIcon name="sentences" {...props} />,
  words: (props) => <SvgIcon name="words" {...props} />,
  solved: (props) => <SvgIcon name="solved" {...props} />,
  cefr: (props) => <SvgIcon name="cefr" {...props} />,
  topic: (props) => <SvgIcon name="topic" {...props} />,
  time: (props) => <SvgIcon name="time" {...props} />,
  bigmic: (props) => <SvgIcon name="bigmic" {...props} />,
  date: (props) => <SvgIcon name="date" {...props} />,
  type: (props) => <SvgIcon name="type" {...props} />,
  report: (props) => <SvgIcon name="report" {...props} />,
  report1: (props) => <SvgIcon name="report1" {...props} />,
  report2: (props) => <SvgIcon name="report2" {...props} />,
  report3: (props) => <SvgIcon name="report3" {...props} />,
  report4: (props) => <SvgIcon name="report4" {...props} />,
  bigcheck: (props) => <SvgIcon name="bigcheck" {...props} />,
  school: (props) => <SvgIcon name="school" {...props} />,
  campus: (props) => <SvgIcon name="campus" {...props} />,
  classroom: (props) => <SvgIcon name="classroom" {...props} />,
  record: (props) => <SvgIcon name="record" {...props} />,
  play: (props) => <SvgIcon name="play" {...props} />,
  pause: (props) => <SvgIcon name="pause" {...props} />,
  stop: (props) => <SvgIcon name="stop" {...props} />,
  recorddone: (props) => <SvgIcon name="recorddone" {...props} />,
  close: (props) => <SvgIcon name="close" {...props} />,
  hourglass: (props) => <SvgIcon name="hourglass" {...props} />,

};

export const getIconSource = (name) => icons[name] ?? null;